---

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: yum Update
    yum: update_cache=yes
    
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert nginx conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: Start NGiNX
    systemd:
      name: nginx
      state: started
      enabled: yes

...
